engineering/calc_app/urls.py
from django.urls import path
from . import views

app_name = 'calc_app'

urlpatterns = [
    path('section_prop/', views.rectangle, name='rectangle'),
    path('fan_unbalance/', views.fan_unbalance, name="fan_unbalance")
]

engineering/engineering/urls.py
from django.contrib import admin
from django.urls import path, include
from calc_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('calc_app/', include('calc_app.urls')),

]

engineering/calc_app/models.py
from django.db import models
import datetime
from django import forms

# Create your models here.


class Rectangle(models.Model):
    rec_width = models.DecimalField(max_digits=10, decimal_places=2)
    rec_height = models.DecimalField(max_digits=10, decimal_places=2)
    date_recorded = models.DateField(auto_now=True)


class FanUnbalance(models.Model):
    BALANCE_CHOICE = ['1', '2.5', '6.3']
    balance_grade = models.CharField(max_length=10, choices=[(x, x) for x in BALANCE_CHOICE], default='2.5')
    impeller_mass = models.DecimalField(max_digits=10, decimal_places=2)
    fan_speed = models.DecimalField(max_digits=10, decimal_places=2)
    backplate_dia = models.DecimalField(max_digits=10, decimal_places=2)

engineering/calc_app/forms.py
from django import forms
from .models import Rectangle, FanUnbalance


class RectangleForm(forms.ModelForm):
    class Meta():
        model = Rectangle
        fields = '__all__'


class FanUnbalanceForm(forms.ModelForm):
    class Meta():
        model = FanUnbalance
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['balance_grade'].widget.attrs.update({'class': 'special'})
        self.fields['impeller_mass'].widget.attrs.update({'class': 'special'}, size='200')

engineering/calc_app/views.py
from django.shortcuts import render
from calc_app.forms import RectangleForm, FanUnbalanceForm
from lib.rectangle_properties import Rect
from lib.fan_unbalance import Fan
from . models import Rectangle, FanUnbalance

# Create your views here.


def index(request):
    return render(request, 'index.html')


def rectangle(request):

    form = RectangleForm()

    if request.method == 'POST':
        form = RectangleForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            x = float(form.cleaned_data['rec_width'])
            y = float(form.cleaned_data['rec_height'])

            arta = Rect(x, y)
            result1 = arta.area()
            result2 = round(arta.p_moment(), 2)
            result3 = "Area = "
            result4 = "Principal Moment of Inertia = "

            return render(request, 'section_prop.html', {'form': form, 'result1': result1, 'result2': result2, 'result3': result3, 'result4': result4})
        else:
            print('Form Invalid')

    return render(request, 'section_prop.html', {'form': form})


def fan_unbalance(request):
    form = FanUnbalanceForm()

    if request.method == 'POST':
        form = FanUnbalanceForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            A = float(form.cleaned_data['balance_grade'])
            B = float(form.cleaned_data['impeller_mass'])
            C = float(form.cleaned_data['fan_speed'])
            D = float(form.cleaned_data['backplate_dia'])

            fan = Fan(A, B, C, D)
            result1 = fan.pru()
            result2 = fan.patch_area()
            result3 = "Premissable Residual Unbalance = "
            result4 = "Max. Patch Area = "

            return render(request, 'fan_unbalance.html', {'form': form, 'result1': result1, 'result2': result2, 'result3': result3, 'result4': result4})
        else:
            print('Form Invalid')

    return render(request, 'fan_unbalance.html', {'form': form})

engineering/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">


          <li><a class="navbar-brand" href="{% url 'index' %}">HOME</a></li>
          <li><a class="navbar-link" href="{% url 'calc_app:rectangle' %}">Rectangle</a></li>
          <li><a class="navbar-link" href="{% url 'calc_app:fan_unbalance' %}">Fan Unbalance</a></li>



        </ul>
      </div>
    </nav>

            {% block body_block %}
            {% endblock %}

    </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

engineering/templates/fan_unbalance.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h2 class="mt-2">Fan Unpalance Calculator</h2>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
    <!-- <div class="container">
        <div class="jumbotron"> -->

   <!-- <h1>FAN UNBALANCE</h1>
   <form class="form-group row" method="POST">
    <div class="col-sm-10"> -->
    <div class="container">
        <div class="jumbotron">
      <form method="POST" novalidate>
          <div class="row">
              <div class="col-6">
                 {{ form.balance_grade|as_crispy_field }}
              </div>
              <div class="col-6">
                  {{ form.impeller_mass|as_crispy_field }}
               </div>
               <div class="col-6">
                  {{ form.fan_speed|as_crispy_field }}
               </div>
               <div class="col-6">
                  {{ form.backplate_dia|as_crispy_field }}
               </div>
        {% csrf_token %}
      <div class="col-sm-10">
          <button type="submit" class="btn btn-success">Submit</button>      <!-- </div>
    </div> -->

   </form>

</div>
</div>
</div>

<div>
<p></p>
<p></p>
<hr>
<h4>{{ result3}}<span style="color:blue">{{ result1 }}</span></h4>
<p></p>
<hr>
<h4>{{ result4 }}<span style="color:blue">               {{ result2 }}</span></h4>
</div>
{% endblock %}

engineering/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h1 class="mt-2">Calculator</h1>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
<div class="container">
        <div class="jumbotron">
   <h2>Please selece calculation page</h2>

   <a href="calc_app/section_prop">Section Properties</a>
   <br>
   <a href="calc_app/fan_unbalance">Fan Unbalance</a>

</div>
</div>
   {% endblock %}

engineering/templates/section_prop.html
{% extends "base.html" %}

{% block body_block %}
<div class="container">
        <div class="row justify-content-center">
          <div class="col-8">
            <h2 class="mt-2">Rectangular Section Properties Calculator</h2>
            <hr class="mt-0 mb-4">
            </div>
        </div>
      </div>
    <div class="container">
        <div class="jumbotron">
      <form method="POST">
        {{ form.as_p}}
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Submit</button>

   </form>

</div>
<p></p>
<p></p>
<hr>
<h4>{{result3}}   <span style="color:blue">{{ result1 }} </span> </h4>
<p></p>
<hr>
<h4>{{result4}}<span style="color:blue">{{ result2 }} </span> </h4>
</div>
{% endblock %}